### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by cigoic** [JamesBrill/react-speech-recognition#135]
Hi, I just tried the sample code on README (copy and paste). But got an error as shown below.
Any idea to solve this? 

Thanks.

```
Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in span (created by Dictaphone)
    in Dictaphone (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog
at node_modules/react-native/Libraries/ReactNative/renderApplication.js:58:4 in renderApplication
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:117:25 in runnables.appKey.run
at node_modules/react-native/Libraries/ReactNative/AppRegistry.js:202:4 in runApplication

Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in span (created by Dictaphone)
    in Dictaphone (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in DevAppContainer (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```

**Comment by cigoic** [comment]
wow...Thanks a lot!
It's a very helpful repository.

**Comment by morenoh149** [comment]
@JamesBrill the react-native-voice project seems to have stalled. Is there any way to use react-speech-recognition within a reactNative app and rely on an internet connect with cloud speech apis?
