### ISSUE TITLE
Invalid hook calls 

### ISSUE THREAD

**Issue by vanilladucky** [JamesBrill/react-speech-recognition#153]
I seemed to have copied the exact code given in the example and done everything necessary, including installation. However, the following error arrises

```
react.development.js:209 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

& 

```
react.development.js:1622 Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at useState (react.development.js:1622:1)
    at useSpeechRecognition (SpeechRecognition.js:65:1)
    at Dictaphone (dictaphone.js:26:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
```

**Comment by smorimoto** [comment]
If you are still experiencing issues, please re-open with more detailed environmental information and/or an MRE.
